version: '0.0.0-{build}'

image: Visual Studio 2017

platform:
  - x64

clone_folder: c:\projects\vcpkg-experimental-ports
skip_tags: true

environment:
  VCPKG_ROOT: C:\Tools\vcpkg

init:
  - cmd: cmake --version
  - cmd: msbuild /version
 
configuration:
  - Debug
  - Release

install:
  - cmd: git submodule update --init --recursive
  - cmd: cd C:\Tools\vcpkg
  - cmd: git pull --ff -q

build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: C:\Python37-x64\python.exe ./tools/vcpkg/setup.py --vcpkg-dir=c:/tools/vcpkg

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
