version: '0.0.0-{build}'

image: Visual Studio 2017

platform:
  - x64

clone_folder: c:\projects\vcpkg-experimental-ports
skip_tags: true

environment:
  VULKAN_SDK: C:\VulkanSDK\1.1.97.0
  VCPKG_ROOT: C:\Tools\vcpkg

init:
  - cmd: cmake --version
  - cmd: msbuild /version
 
configuration:
  - Debug

install:
  - cmd: git submodule update --init --recursive
  - cmd: curl --silent --show-error --output VulkanSDK.exe https://cwfitz.com/s/19028-082433-VulkanSDK-1.1.97.0-Installer.exe
  - cmd: .\VulkanSDK.exe /S
  - cmd: cd C:\Tools\vcpkg
  - cmd: git pull --ff -q
  - cmd: C:\Tools\vcpkg\bootstrap-vcpkg.bat

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: C:\Python37-x64\python.exe ./tools/vcpkg/setup.py --vcpkg-dir=c:/tools/vcpkg

cache: 
  - c:\tools\vcpkg\downloads\ -> tools/ci/appveyor.yaml tools/vcpkg/setup.py
  - c:\tools\vcpkg\installed\ -> tools/ci/appveyor.yaml tools/vcpkg/setup.py
  - c:\tools\vcpkg\packages\ -> tools/ci/appveyor.yaml tools/vcpkg/setup.py

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL

on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
